<?php

/**
 * Language strings that are intentionally identical to English.
 *
 * Keys use the form "ARRAY:key". Numeric and string keys are both represented
 * by their displayed key value without quotes.
 *
 * Keep this list conservative: add entries only when the English spelling is
 * also the normal spelling in the target language.
 */

return [
    'italian_utf-8.php' => [
        'LANG01:57',
        'LANG01:68',
        'LANG01:90',
        'LANG20:5',
        'LANG21:6',
        'LANG21:block_type_portal',
        'LANG24:36',
        'LANG24:80',
        'LANG27:51',
        'LANG27:breadcrumb_root',
        'LANG28:5',
        'LANG28:8',
        'LANG29:core',
        'LANG32:21',
        'LANG32:59',
        'LANG33:21',
        'LANG_ACCESS:no',
        'LANG_ADMIN:info',
        'LANG_ADMIN:computer',
        'LANG_BUTTONS:1',
        'LANG_BUTTONS:11',
        'LANG_CONFIG:home',
        'LANG_LIKES:autotag_desc_likes_block',
        'LANG_MONTH_SHORT:2',
        'LANG_MONTH_SHORT:4',
        'LANG_MYACCOUNT:pe_privacy',
        'LANG_ROUTER:24',
    ],
    'spanish_argentina_utf-8.php' => [
        'LANG01:34',
        'LANG03:17',
        'LANG04:21',
        'LANG21:6',
        'LANG21:block_type_portal',
        'LANG24:36',
        'LANG24:80',
        'LANG24:95',
        'LANG27:51',
        'LANG28:22',
        'LANG32:21',
        'LANG33:21',
        'LANG_ACCESS:no',
        'LANG_DB_BACKUP:bytes',
        'LANG_TRB:send_error',
        'LANG_ROUTER:24',
    ],
    'spanish_utf-8.php' => [
        'LANG01:34',
        'LANG03:17',
        'LANG04:21',
        'LANG21:6',
        'LANG21:block_type_portal',
        'LANG24:36',
        'LANG24:80',
        'LANG24:95',
        'LANG27:51',
        'LANG28:22',
        'LANG32:21',
        'LANG33:21',
        'LANG_ACCESS:no',
        'LANG_DB_BACKUP:bytes',
        'LANG_TRB:send_error',
        'LANG_ROUTER:24',
    ],
    'german_utf-8.php' => [
        'LANG04:6',
        'LANG21:block_type_gldefault',
        'LANG21:block_type_portal',
        'LANG24:80',
        'LANG24:95',
        'LANG28:8',
        'LANG_ACCESS:name',
        'LANG_ADMIN:computer',
        'LANG_DB_BACKUP:bytes',
        'LANG_ENVCHECK:status',
        'LANG_LOGVIEW:logs',
        'LANG_MONTH:4',
        'LANG_MONTH:8',
        'LANG_MONTH:9',
        'LANG_MONTH:11',
        'LANG_TRB:service_website',
    ],
    'german_formal_utf-8.php' => [
        'LANG04:6',
        'LANG21:block_type_gldefault',
        'LANG21:block_type_portal',
        'LANG24:80',
        'LANG24:95',
        'LANG28:8',
        'LANG_ACCESS:name',
        'LANG_ADMIN:computer',
        'LANG_DB_BACKUP:bytes',
        'LANG_ENVCHECK:status',
        'LANG_LOGVIEW:logs',
        'LANG_MONTH:4',
        'LANG_MONTH:8',
        'LANG_MONTH:9',
        'LANG_MONTH:11',
        'LANG_TRB:service_website',
    ],
];
